FROM dfars-kit/ansible
MAINTAINER Ahmed Masud <ahmed.masud@trustifier.com>

RUN yum update -y && yum clean all
RUN yum install -y  http://resources.ovirt.org/pub/yum-repo/ovirt-release40.rpm
RUN yum install -y  ovirt-engine


ENTRYPOINT [ "/usr/sbin/sshd", "-D" ]
